-- ============================================================================
-- V10__mates.sql — 메이트(지속 관계) 신청·수락 도메인.
-- mate_requests: 신청. status를 보관(삭제 안 함)하고, 진행 중(PENDING) 동일 쌍만 유일하게 강제.
--   → 거절/취소 후 같은 상대 재신청 허용(종료 상태 행은 이력으로 누적).
-- mates: 수락 시 양방향 2행(a→b, b→a) 저장 → 내 메이트 조회는 WHERE user_id=:me 로 단순.
-- ============================================================================
CREATE TABLE mate_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status        VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMP   NOT NULL,
    responded_at  TIMESTAMP
);
CREATE UNIQUE INDEX uq_mate_requests_pending
    ON mate_requests(from_user_id, to_user_id) WHERE status = 'PENDING';
CREATE INDEX idx_mate_requests_to   ON mate_requests(to_user_id);
CREATE INDEX idx_mate_requests_from ON mate_requests(from_user_id);

CREATE TABLE mates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mate_user_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT uq_mates_pair UNIQUE (user_id, mate_user_id)
);
CREATE INDEX idx_mates_user ON mates(user_id);
