-- ============================================================================
-- V13__notifications.sql — 인앱 알림함(NOTI-003).
-- 같이먹기/메이트 신청·수락 시 도메인 서비스가 같은 트랜잭션에서 INSERT.
-- 문구는 저장하지 않는다(앱이 type+actor 닉네임으로 조립 — 문구 변경이 과거 알림에도 적용).
-- 미래 푸시(NOTI-001/002)는 이 레코드 발행 지점에 기기 발송만 얹는다.
-- ============================================================================
CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    actor_user_id BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    type          VARCHAR(30) NOT NULL,
    is_read       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL
);
CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread  ON notifications(user_id) WHERE is_read = FALSE;

COMMENT ON TABLE  notifications               IS '인앱 알림함. 도메인 이벤트(같이먹기/메이트 신청·수락) 발생 시 수신자별로 쌓인다.';
COMMENT ON COLUMN notifications.id            IS '알림 PK';
COMMENT ON COLUMN notifications.user_id       IS '받는 사람(users FK). 사용자 삭제 시 알림도 삭제';
COMMENT ON COLUMN notifications.actor_user_id IS '알림을 일으킨 상대(신청자/수락자). 닉네임 표시용. 상대 탈퇴 시 NULL';
COMMENT ON COLUMN notifications.type          IS '알림 종류: MEAL_REQUEST_RECEIVED/MEAL_REQUEST_ACCEPTED/MATE_REQUEST_RECEIVED/MATE_REQUEST_ACCEPTED';
COMMENT ON COLUMN notifications.is_read       IS '읽음 여부(개별 탭 또는 모두 읽음으로 true)';
COMMENT ON COLUMN notifications.created_at    IS '발생 시각(KST naive — 프로젝트 공통 컨벤션)';
