-- ============================================================================
-- V14__blocks_reports.sql — 차단/신고(FR-108 안전장치).
-- blocks: 한 방향만 저장(blocker→blocked). "완전 상호 은닉"은 조회 시 양방향(OR) 검사로 구현.
--   A·B가 서로 차단하면 2행 존재 가능(정상). 재차단은 uq 위반 → 409.
-- reports: 다형 대상(USER/REVIEW) — target_id에 FK 없음(대상 삭제·탈퇴 후에도 내역 보존).
--   target_nickname은 표시용 스냅샷. status는 관리자 툴 도입 대비 예약(현재 전부 RECEIVED).
-- ============================================================================
CREATE TABLE blocks (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_blocks_pair UNIQUE (blocker_id, blocked_id),
    CONSTRAINT ck_blocks_not_self CHECK (blocker_id <> blocked_id)
);
CREATE INDEX idx_blocks_blocked ON blocks(blocked_id);

COMMENT ON TABLE blocks IS '유저 차단(한 방향 저장, 조회는 양방향 검사)';
COMMENT ON COLUMN blocks.id IS 'PK';
COMMENT ON COLUMN blocks.blocker_id IS '차단한 사람(users FK)';
COMMENT ON COLUMN blocks.blocked_id IS '차단당한 사람(users FK)';
COMMENT ON COLUMN blocks.created_at IS '차단 시각(KST 벽시계)';

CREATE TABLE reports (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type     VARCHAR(20)  NOT NULL,
    target_id       BIGINT       NOT NULL,
    target_nickname VARCHAR(20)  NOT NULL,
    reason_code     VARCHAR(30)  NOT NULL,
    detail          VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'RECEIVED',
    created_at      TIMESTAMP    NOT NULL
);
CREATE INDEX idx_reports_reporter ON reports(reporter_id);

COMMENT ON TABLE reports IS '신고 접수(대상: USER/REVIEW 다형, FK 없음 — 내역 보존)';
COMMENT ON COLUMN reports.id IS 'PK';
COMMENT ON COLUMN reports.reporter_id IS '신고자(users FK)';
COMMENT ON COLUMN reports.target_type IS '신고 대상 종류(USER/REVIEW)';
COMMENT ON COLUMN reports.target_id IS '대상 id(USER면 users.id, REVIEW면 reviews.id) — FK 없음';
COMMENT ON COLUMN reports.target_nickname IS '표시용 스냅샷(유저 닉네임/리뷰 작성자 닉네임)';
COMMENT ON COLUMN reports.reason_code IS '신고 사유 코드(INAPPROPRIATE_MESSAGE/ABUSE/SPAM/FALSE_PROFILE/OTHER)';
COMMENT ON COLUMN reports.detail IS '선택 상세 설명(최대 500자)';
COMMENT ON COLUMN reports.status IS '처리 상태(RECEIVED/REVIEWING/RESOLVED) — 현재 전부 RECEIVED, 관리자 툴 대비 예약';
COMMENT ON COLUMN reports.created_at IS '접수 시각(KST 벽시계)';
