-- ============================================================================
-- V15__notices.sql — 공지사항.
-- 운영자가 DB 직접 INSERT로 등록(관리자 API 없음), 앱은 조회 전용.
-- published_at이 미래면 미노출(예약 게시 겸 초안). 내리려면 published_at을 미래로.
-- ============================================================================
CREATE TABLE notices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(20)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         TEXT,
    pinned       BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP    NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_notices_list ON notices (pinned DESC, published_at DESC);

COMMENT ON TABLE  notices              IS '공지사항 — 운영자가 DB로 직접 등록, 앱은 조회 전용';
COMMENT ON COLUMN notices.category     IS '카테고리: UPDATE(업데이트)/EVENT(이벤트)/GENERAL(안내)';
COMMENT ON COLUMN notices.title        IS '제목';
COMMENT ON COLUMN notices.body         IS '본문(펼침 영역). NULL이면 제목만 표시';
COMMENT ON COLUMN notices.pinned       IS '상단 고정 여부';
COMMENT ON COLUMN notices.published_at IS '게시 시각(KST naive). 미래면 미노출 — 예약 게시 겸 초안';
