-- ============================================================================
-- V16__notification_settings.sql — 사용자별 알림 수신 설정(NOTI-004).
-- 1인 1행(lazy — 행 없으면 기본값). off면 발행 시점에 해당 알림을 생성하지 않는다.
-- 공지·이벤트(marketing)는 현재 발행 지점이 없는 미래용 컬럼.
-- ============================================================================
CREATE TABLE notification_settings (
    id                BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT  NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    meal_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    mate_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    notice_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    marketing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL
);

COMMENT ON TABLE  notification_settings                   IS '사용자별 알림 수신 설정(1인 1행, lazy — 행 없으면 기본값). off면 발행 시점에 해당 알림을 생성하지 않는다.';
COMMENT ON COLUMN notification_settings.user_id           IS '사용자(users FK, 유니크). 사용자 삭제 시 함께 삭제';
COMMENT ON COLUMN notification_settings.meal_enabled      IS '같이먹기 신청·수락 알림 수신(기본 true)';
COMMENT ON COLUMN notification_settings.mate_enabled      IS '메이트 신청·수락 알림 수신(기본 true)';
COMMENT ON COLUMN notification_settings.notice_enabled    IS '공지사항 알림 수신(기본 true, 미래용 — 현재 발행 지점 없음)';
COMMENT ON COLUMN notification_settings.marketing_enabled IS '이벤트·혜택(광고성) 알림 수신 동의(기본 false 옵트인, 미래용)';
COMMENT ON COLUMN notification_settings.created_at        IS '생성 시각(KST naive)';
COMMENT ON COLUMN notification_settings.updated_at        IS '수정 시각(KST naive)';
