-- ============================================================================
-- V1__core.sql — 혼정 P1(MVP) 핵심 스키마 (PostgreSQL)
-- 스키마의 source of truth. JPA는 ddl-auto: validate로 이 스키마를 검증만 한다.
-- 단계: P1 = 인증 전환 + 체크인 핵심 루프 + 같이먹기.
-- 알림은 폴링 → device_tokens/notifications 없음. reactions 보류. (계획서 참조)
-- ============================================================================

-- A. 인증·계정 ---------------------------------------------------------------

-- 회원. phone/nickname은 1차 식별자이나 온보딩(status=PENDING) 동안엔 NULL 허용,
-- /auth/complete 에서 채워지고 status=ACTIVE 로 전환된다(애플리케이션이 강제).
CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone              VARCHAR(20)  UNIQUE,                 -- 휴대폰(인증완료)·1차 식별자
    email              VARCHAR(255),                        -- OAuth 제공(선택)
    nickname           VARCHAR(50)  UNIQUE,                 -- 표시 이름(중복확인)
    profile_image_url  VARCHAR(500),
    gender             VARCHAR(10),                         -- MALE|FEMALE|NONE
    age_group          VARCHAR(10),                         -- 10s|20s|30s|40s|50+
    introduction       VARCHAR(150),
    region             VARCHAR(100),                        -- 동네(시군구·동)
    region_lat         DOUBLE PRECISION,
    region_lng         DOUBLE PRECISION,
    dining_style       VARCHAR(20),                         -- TALK|QUIET
    allow_meal_request BOOLEAN     NOT NULL DEFAULT TRUE,    -- 같이먹기 수신 opt-in
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING|ACTIVE|SUSPENDED|WITHDRAWN
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL
);

-- refresh 토큰(DB 저장 + 회전). 원문 대신 해시 저장, 로그아웃/탈취 시 revoke.
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP   NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

-- 소셜 로그인 연동(공급자 토큰은 저장하지 않고 식별만).
CREATE TABLE social_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users(id),
    provider         VARCHAR(10) NOT NULL,                  -- KAKAO|APPLE
    provider_user_id VARCHAR(255) NOT NULL,                 -- 공급자측 고유 sub
    email            VARCHAR(255),
    created_at       TIMESTAMP   NOT NULL,
    updated_at       TIMESTAMP   NOT NULL,
    CONSTRAINT uq_social_provider_user UNIQUE (provider, provider_user_id)
);

-- 휴대폰 인증(회원과 무관한 발송도 있어 phone 기준). 코드는 해시 저장 권장.
CREATE TABLE phone_verifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone      VARCHAR(20) NOT NULL,
    code       VARCHAR(6)  NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    verified   BOOLEAN     NOT NULL DEFAULT FALSE,
    attempts   INT         NOT NULL DEFAULT 0,
    created_at TIMESTAMP   NOT NULL
);
CREATE INDEX idx_phone_verifications_phone_created ON phone_verifications(phone, created_at);

-- 약관 동의(사용자당 1행). 필수 3종(service·privacy·location), 선택(marketing).
CREATE TABLE terms_agreements (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT    NOT NULL UNIQUE REFERENCES users(id),
    service   BOOLEAN   NOT NULL,
    privacy   BOOLEAN   NOT NULL,
    location  BOOLEAN   NOT NULL,
    marketing BOOLEAN   NOT NULL DEFAULT FALSE,
    agreed_at TIMESTAMP NOT NULL
);

-- B. 장소 -------------------------------------------------------------------

-- 카카오 장소 캐시. external_id 기준 upsert. (business_hours JSONB는 P2로 보류)
CREATE TABLE places (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id  VARCHAR(64)  NOT NULL UNIQUE,              -- 카카오 place id(캐싱 키)
    name         VARCHAR(255) NOT NULL,
    address      VARCHAR(255),
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    category     VARCHAR(100),
    phone        VARCHAR(30),
    homepage_url VARCHAR(500),
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_places_lat_lng ON places(latitude, longitude);

-- C. 체크인·연결 -------------------------------------------------------------

-- 혼밥 체크인(핵심 데이터). 사용자당 ACTIVE 1개만 — 부분 유니크 인덱스로 강제.
CREATE TABLE check_ins (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    place_id   BIGINT      NOT NULL REFERENCES places(id),
    status     VARCHAR(10) NOT NULL,                        -- ACTIVE|ENDED
    started_at TIMESTAMP   NOT NULL,
    ended_at   TIMESTAMP,
    created_at TIMESTAMP   NOT NULL
);
-- 단일 활성 체크인 불변식(JPA로 표현 불가 → SQL 전용). H2는 미지원이라 Postgres 사용.
CREATE UNIQUE INDEX uq_check_ins_active_user ON check_ins(user_id) WHERE status = 'ACTIVE';
CREATE INDEX idx_check_ins_status_started ON check_ins(status, started_at); -- 통계 집계
CREATE INDEX idx_check_ins_place_status   ON check_ins(place_id, status);   -- 지도 마커·혼밥러 목록

-- 같이먹기 신청. 수신자는 to_check_in_id → check_ins.user_id 로 식별.
CREATE TABLE meal_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id   BIGINT      NOT NULL REFERENCES users(id),
    to_check_in_id BIGINT      NOT NULL REFERENCES check_ins(id),
    place_id       BIGINT      NOT NULL REFERENCES places(id),
    message        VARCHAR(200),                            -- 인사 한마디
    status         VARCHAR(10) NOT NULL DEFAULT 'PENDING',  -- PENDING|ACCEPTED|DECLINED
    created_at     TIMESTAMP   NOT NULL,
    responded_at   TIMESTAMP,
    CONSTRAINT uq_meal_request_from_target UNIQUE (from_user_id, to_check_in_id) -- 중복 신청 방지
);
CREATE INDEX idx_meal_requests_target_status ON meal_requests(to_check_in_id, status);
