-- ============================================================================
-- V5__user_food_preferences.sql — 선호 음식(ERD A-6). 사용자당 1행(UNIQUE), 최대 3개를
-- 고정 컬럼(food1/food2/food3)으로 보관. P2 항목을 앞당겨 구현.
-- ============================================================================
CREATE TABLE user_food_preferences (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL UNIQUE REFERENCES users(id),  -- 사용자당 1행
    food1      VARCHAR(50),
    food2      VARCHAR(50),
    food3      VARCHAR(50),
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);
