-- ============================================================================
-- V6__reviews.sql — 리뷰=혼밥일기(ERD F). reviews(별점 2종 NOT NULL·인증 체크인 선택) +
-- review_tags(친화태그, place_id 역정규화로 식당별 집계). 사진(review_photos)은 다음 슬라이스.
-- ============================================================================
CREATE TABLE reviews (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL REFERENCES users(id),
    check_in_id          BIGINT      REFERENCES check_ins(id),     -- 있으면 인증(NULL 허용)
    place_id             BIGINT      NOT NULL REFERENCES places(id),
    visited_at           TIMESTAMP   NOT NULL,
    content              TEXT,
    taste_rating         SMALLINT    NOT NULL CHECK (taste_rating BETWEEN 1 AND 5),
    solo_friendly_rating SMALLINT    NOT NULL CHECK (solo_friendly_rating BETWEEN 1 AND 5),
    created_at           TIMESTAMP   NOT NULL,
    updated_at           TIMESTAMP   NOT NULL
);
CREATE INDEX idx_reviews_user_visited  ON reviews(user_id, visited_at DESC);
CREATE INDEX idx_reviews_place_created ON reviews(place_id, created_at DESC);

CREATE TABLE review_tags (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT      NOT NULL REFERENCES reviews(id),
    place_id  BIGINT      NOT NULL REFERENCES places(id),  -- reviews에서 역정규화(불변)
    tag       VARCHAR(30) NOT NULL
);
CREATE INDEX idx_review_tags_place_tag ON review_tags(place_id, tag);
CREATE INDEX idx_review_tags_review    ON review_tags(review_id);
