-- ============================================================================
-- V8__review_photos.sql — 리뷰 사진(ERD F-2). 리뷰 UGC가 식당 사진탭 갤러리의 출처.
-- review 1:N photo. sort_order로 표시 순서 유지. review 삭제 시 함께 삭제(FK CASCADE).
-- ============================================================================
CREATE TABLE review_photos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  BIGINT       NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    image_url  VARCHAR(500) NOT NULL,
    sort_order INT          NOT NULL,
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_review_photos_review ON review_photos(review_id, sort_order);
