CREATE TABLE favorite_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       VARCHAR(40)  NOT NULL,
    note       VARCHAR(120),
    color      VARCHAR(20)  NOT NULL DEFAULT '#FF5A1F',
    is_default BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_favorite_groups_user ON favorite_groups(user_id);

CREATE TABLE favorites (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT    NOT NULL REFERENCES favorite_groups(id) ON DELETE CASCADE,
    place_id   BIGINT    NOT NULL REFERENCES places(id)          ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_favorites_group_place UNIQUE (group_id, place_id)
);
CREATE INDEX idx_favorites_group ON favorites(group_id);
CREATE INDEX idx_favorites_place ON favorites(place_id);

-- 기존 유저 백필: 전원에게 기본 '즐겨찾기' 그룹 1개
INSERT INTO favorite_groups (user_id, name, note, color, is_default, created_at, updated_at)
SELECT id, '즐겨찾기', NULL, '#FF5A1F', TRUE, now(), now() FROM users;
